#!/bin/bash
# INICIO RÁPIDO DEL PROYECTO

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🚀 INICIO RÁPIDO - API BACKEND NODE.JS + EXPRESS + MYSQL  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ PASO 1: Dependencias instaladas"
echo "   ✓ express"
echo "   ✓ mysql2"
echo "   ✓ jwt"
echo "   ✓ bcrypt"
echo "   ✓ dotenv"
echo "   ✓ cors"
echo ""

echo "✅ PASO 2: Estructura del proyecto creada"
echo "   ✓ /src/config"
echo "   ✓ /src/controllers"
echo "   ✓ /src/routes"
echo "   ✓ /src/middlewares"
echo "   ✓ /src/models"
echo ""

echo "⚠️  PASO 3: Configurar Base de Datos"
echo "   📝 Edita el archivo .env con tus credenciales:"
echo ""
echo "   # OPCIÓN A: Usar db4free.net (Recomendado)"
echo "   DB_HOST=db4free.net"
echo "   DB_USER=tu_usuario"
echo "   DB_PASSWORD=tu_contraseña"
echo "   DB_NAME=tu_base_de_datos"
echo ""
echo "   # OPCIÓN B: Usar MySQL local"
echo "   DB_HOST=localhost"
echo "   DB_USER=root"
echo "   DB_PASSWORD=tu_contraseña"
echo "   DB_NAME=api_backend"
echo ""

echo "🔐 IMPORTANTE: Cambiar JWT_SECRET"
echo "   Reemplaza: your_super_secret_jwt_key_change_this_in_production"
echo "   Con una clave aleatoria larga y segura"
echo ""

echo "🚀 PASO 4: Iniciar Servidor"
echo ""
echo "   DESARROLLO (con auto-reload):"
echo "   $ npm run dev"
echo ""
echo "   PRODUCCIÓN:"
echo "   $ npm start"
echo ""

echo "🐳 PASO 5: Usar Docker (Opcional)"
echo ""
echo "   Compilar imagen:"
echo "   $ docker build -t api-backend ."
echo ""
echo "   Ejecutar contenedor:"
echo "   $ docker run -p 3000:3000 --env-file .env api-backend"
echo ""
echo "   O con Docker Compose:"
echo "   $ docker-compose up -d"
echo ""

echo "🧪 PASO 6: Probar API"
echo ""
echo "   Endpoint de prueba:"
echo "   GET http://localhost:3000/"
echo ""
echo "   Registro:"
echo "   POST http://localhost:3000/auth/register"
echo "   Body: { email, password, confirmPassword }"
echo ""
echo "   Login:"
echo "   POST http://localhost:3000/auth/login"
echo "   Body: { email, password }"
echo ""
echo "   CRUD Items (requiere token JWT):"
echo "   GET /api/items"
echo "   POST /api/items"
echo "   PUT /api/items/:id"
echo "   DELETE /api/items/:id"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     📚 Ver README.md para documentación completa           ║"
echo "║     🔗 http://localhost:3000 (después de iniciar)          ║"
echo "╚════════════════════════════════════════════════════════════╝"
